#!/bin/sh
# center current window

. $HOME/.config/wm.conf

# get current window id, width and height
WID=$(<$MNT/focused)
WW=$(<$MNT/$WID/geometry/width)
WH=$(<$MNT/$WID/geometry/height)

# get screen width and height
SW=$(<$MNT/root/geometry/width)
SH=$(<$MNT/root/geometry/height)

# move the current window to the center of the screen
echo $(((SW - WW)/2)) > $MNT/$WID/geometry/x
echo $(((SH - WH + PANELHEIGHT)/2)) > $MNT/$WID/geometry/y
