#!/bin/sh
# put current window into a corner

. $HOME/.config/wm.conf

FOCUS=$(<$MNT/focused)
CUR=${2:-$(<$MNT/focused)}
SW=$(<$MNT/root/geometry/width)
SH=$(<$MNT/root/geometry/height)

BW=$(<$MNT/$CUR/border/width)
W=$(<$MNT/$CUR/geometry/width)
H=$(<$MNT/$CUR/geometry/height)

case $1 in
	tl)	X=$GAP Y=$((GAP + PANELHEIGHT)) ;;
	tr)	X=$((SW - W - BW*2 - GAP)) Y=$((GAP + PANELHEIGHT)) ;;
	bl)	X=$GAP Y=$((SH - H - BW*2 - GAP)) ;;
	br)	X=$((SW - W - BW*2 - GAP)) Y=$((SH - H - BW*2 - GAP)) ;;
	*)	echo "no position specified" 
		exit ;;
esac

echo $X > $MNT/$CUR/geometry/x
echo $Y > $MNT/$CUR/geometry/y
