#!/bin/sh
# focus wrapper that sets borders and can focus next/previous window

. $HOME/.config/wm.conf

a=0xb8b8c8 # active border color
i=0x1a1a26 # inactive border color

# get current window id
c=$(<$MNT/focused)

setborder() {
	# check if window exists
	[ -e $MNT/$2 ] || return
	
	echo $BORDERWIDTH > $MNT/$2/border/width

	case $1 in
		active)	echo $a > $MNT/$2/border/color ;;
		inactive) echo $i > $MNT/$2/border/color ;;
	esac
}

case $1 in
	next) wid=$(ls $MNT|grep -v $c|grep -v root|grep -v event|grep -v focused|sed '1 p;d') ;;
	prev) wid=$(ls $MNT|grep -v $c|grep -v root|grep -v event|grep -v focused|sed '$ p;d') ;;
	0x*) [ -e $MNT/$1 ] && wid=$1 ;;
esac

# exit if another window to focus can't be found
test -z "$wid" && echo "can't find a window to focus" >&2 && exit 1

# set inactive border on current window
setborder inactive $c
# activate the new window
setborder active $wid
# put it on top of the stack
echo raise > $MNT/$wid/stack
# set focus on it
echo $wid > $MNT/focused
