#!/bin/sh
# le (window) advent daemon
# ^ backronym, I just wanted to make the "exec wew | lad" pun on my xinitrc

. $HOME/.config/wm.conf

while IFS=": " read ev wid; do
	case $ev in
		# Focus new windows
		CREATE) $(<$MNT/$wid/ignored) || echo $wid > $MNT/focused ;;

		# Mapping requests
		MAP) $(<$MNT/$wid/ignored) || echo $wid > $MNT/focused  ;;

		# Focus next window when deleting current window
		DESTROY) [ -e $MNT/$(<$MNT/focused) ] || focusw prev 2>/dev/null ;;

		# Focus entered window
		ENTER)  $(<$MNT/$wid/ignored) || echo $wid > $MNT/focused ;;
	esac
done
